Re-point download URL to the archive folder
minio/homebrew-stable pull request #35
Opened 2021-05-13 12:23 UTC by jhvhs

The latest version, `RELEASE.2021-05-12T01-29-06Z`, is absent from the main folder:
```
[macOS 11.3.1] $ brew upgrade minio/stable/mc
==> Upgrading 1 outdated package:
minio/stable/mc RELEASE.2021-04-22T17-40-00Z_1 -> RELEASE.2021-05-12T01-29-06Z_1
==> Upgrading minio/stable/mc RELEASE.2021-04-22T17-40-00Z_1 -> RELEASE.2021-05-12T01-29-06Z_1
==> Downloading https://dl.minio.io/client/mc/release/darwin-amd64/mc.RELEASE.2021-05-12T01-29-06Z
#=#=-#  #
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "mc"
Download failed: https://dl.minio.io/client/mc/release/darwin-amd64/mc.RELEASE.2021-05-12T01-29-06Z```

2021-05-13 15:16 UTC, harshavardhana requested changes
This is not the correct fix instead move to latest release.

2021-05-13 17:09 UTC, jhvhs commented
@harshavardhana done

2021-05-13 17:18 UTC, harshavardhana requested changes
We need to update the sha256sum as well @jhvhs you can get that from 

```
curl https://dl.minio.io/client/mc/release/darwin-amd64/mc.RELEASE.2021-05-12T03-10-11Z.sha256sum
b3829df3b8a47407d1ee792686f244943893d838271cb4bbe7fdb2ae6704a4ca mc.RELEASE.2021-05-12T03-10-11Z
```


```
  if OS.mac?
    url "https://dl.minio.io/client/mc/release/darwin-amd64/mc.#{version}"
    sha256 "f4950a8980d333170d4ba3b1551446bb42f4728c4ed98952c10069865c8c83ba"
  elsif OS.linux?
    url "https://dl.minio.io/client/mc/release/linux-amd64/mc.#{version}"
    sha256 "c6156d79af7d8b3b65a3a9ec89a027e3f617e212d73a495cebb18e038459c1aa"
  end
```

2021-05-14 17:41 UTC, harshavardhana commented
Fixed in master closing.

2021-05-14 17:41 UTC, closed without merging